[package]
name = "static-server"
version = "0.2.0"
edition = "2021"

[[bin]]
name = "server"

[features]
debug = ["essentials/dotenv"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
essentials = { tag = "v0.3.1", git = "https://github.com/majksa-dev/rust-essentials", default-features = false, features = ["log", "panic"] }
gateway = { tag = "v0.1.3", git = "https://github.com/majksa-dev/rust-gateway" }
chrono = { version = "0.4.38", default-features = false, features = ["clock", "serde"] }
derive_more = "0.99.18"
futures-util = { version = "0.3.17", default-features = false, features = ["std"] }
rand = "0.8"
slab = "0.4"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0"
envy = "0.4.2"
tokio = { version = "1.38", features = ["full"] }
async-trait = "0.1.80"
http = "1.1.0"

[dev-dependencies]
assert_fs = "1.1.1"
