version: "3.8"

services:
  web:
    build: .
    ports:
      - "8080:80"
    healthcheck:
      test:
        ["CMD", "wget", "-q", "-O", "-", "http://localhost:$$HEALTH_CHECK_PORT"]
      interval: 5s
      timeout: 5s
      start_period: 5s
      retries: 5
    volumes:
      - ./static:/app/static
    environment:
      - RUST_BACKTRACE=0
      - RUST_LOG=info
      - PORT=80
      - HEALTH_CHECK_PORT=9000
      - SERVER_ROOT=/app/static
      - THREADS=16
