version: "3.8"

services:
  web:
    build: .
    ports:
      - "8082:80"
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:9000"]
      interval: 5s
      timeout: 5s
      start_period: 5s
      retries: 5
    volumes:
      - ./static:/app/static
    environment:
      - SERVER_ROOT=/app/static
      - THREADS=16
